name: Build and Publish
on: [ push, pull_request ]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      #Comment
      - name: Get Kobweb
        run: brew install varabyte/tap/kobweb

      # Validate wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      # Build application
      - name: Test and Build
        run: kobweb export --mode dumb

      # If main branch update, deploy to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
